config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :homeworks
  resources :users

   root 'homeworks#index'

end

app/models/homework.rb
class Homework < ActiveRecord::Base
    validates :title, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  
 
    
    has_many :homeworks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :firstname
    devise_parameter_sanitizer.for(:sign_up) << :lastname
    
    devise_parameter_sanitizer.for(:sign_up) << :user_id
  end
  

  
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_filter :get_users
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  # GET /homeworks.json
  def index
   # @homeworks = Homework.all
    @homeworks = Homework.order(end_date: :asc).where(status:false).where("end_date > ?" , DateTime.now)
     @homeworks3 = Homework.order(end_date: :asc).where(status:false).where("end_date < ?" , DateTime.now)
     @homeworks2 = Homework.order(end_date: :asc).where(status:true)
     
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
    
  end

  # GET /homeworks/new
  def new
      @homework = Homework.new
    if user_signed_in?
     @homework = Homework.new
    else
      redirect_to homeworks_path  
      flash.alert = "You must be logged in"
    
    end
  
    
  end

  # GET /homeworks/1/edit
  def edit
    if user_signed_in?
     
    else
      redirect_to homeworks_path
       flash.alert = "You must be logged in"
    end
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
   # @homework = Homework.new(homework_params)
   @homework = current_user.homeworks.new(homework_params)
    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework, notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy

    
    if user_signed_in?
         @homework.destroy
     respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
     end
    else
      redirect_to homeworks_path
       flash.alert = "You must be logged in"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:title, :description, :duration, :start_date, :end_date, :user_id, :status)
     
    end
    
    private
  def get_users
   @users = User.all.map {|user| [user.username,user.id]}
   # @users ||= User.find(self.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homeworks/_form.html.erb
<%= form_for(@homework) do |f| %>
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% @homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.time_select :duration %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Homeworks</h1>

<table>
 
 <table>
  <tbody>
    <div><h3>No Terminadas</h3></div>
 <thead>
    <tr>
      <th>Title</th>
      <th>End date</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
   
   <div><h5>Expiradas</h5></div> 
    <% @homeworks3.each do |homework| %>
      <tr>
        <td><%= homework.title %></td>
        <td><%= homework.end_date %></td>
        <td><%= User.find(id=homework.user_id).username  %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
   
  </tbody>
    </table>
    <table>
     <thead>
    <tr>
      <th>Title</th>
      <th>End date</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
   
   <div><h5>No Expiradas</h5></div> 
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.title %></td>
        <td><%= homework.end_date %></td>
        <td><%= User.find(id=homework.user_id).username  %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
   
  </tbody>
 <table>
  </tbody>
    
</table>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>End date</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
   
   <div><h3>Completadas</h3></div> 
    <% @homeworks2.each do |homework| %>
      <tr>
        <td><%= homework.title %></td>
        <td><%= homework.end_date %></td>
        <td><%= User.find(id=homework.user_id).username  %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
   
  </tbody>
  
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form' %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @homework.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @homework.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @homework.duration %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @homework.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @homework.end_date %>
</p>

<p>
  <strong>Author:</strong>
  <%= @homework.user_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @homework.status %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Trello" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
  <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">Trello</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">


    <!-- Left Nav Section -->
    <ul class="left">
      
       <li><%= link_to 'Homeworks',homeworks_path %>  </li>
    </ul>
    
        <!-- right Nav Section -->
    <ul class="right">
      <% if user_signed_in?%>
        <li>
          <%= link_to current_user.username,edit_user_registration_path %>
        </li>
        <li>
          <%= link_to 'Log Out',destroy_user_session_path, method: :delete %>
        </li>
      <%else%>
       <li class = 'active'>
          <%= link_to 'Sign Up',new_user_registration_path %>
        </li>
        <li>
          <%= link_to 'Sign In',new_user_session_path %>
        </li>
      <%end%>
      
    </ul>
    
  </section>
  </nav>                     
    
    <div class="row">
      <div class="column large-12">
        
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        
        <%= yield %>
      </div>
    </div>
  </body>
</html>